### ISSUE TITLE
Build a portable Jenkins instance for testing

### ISSUE THREAD

**Issue by chelnak** [chelnak/jenkins-tui#1]
Ideally the app should be developed against a dummy instance of Jenkins. This should be some sort of docker based solution.

**Comment by satanb4** [comment]
Hi @chelnak , I am interested in working on this enhancement. Can you please give me the specification of what exactly is required? I can get the framework in place accordingly.

**Comment by chelnak** [comment]
Hey!! I've been developing this against a Jenkins instance that is in use by real people and services. That's not ideal for developing offline or building features that may have an impact on the state of Jenkins.

My thought here was to be able to spin up a test version of Jenkins with something like docker compose that is pre populated with a bunch of dummy jobs, pipelines and maybe a mock agent.

The developer would then do something like:

- docker-compose up
- Update configuration to point to localhost instance of Jenkins

Happy to clarify further if you need ☺️

**Comment by satanb4** [comment]
That sounds good. Basically a mock environment with the Jenkins Master to run some testing basics. Kubernetes will probably be useful, if we wanted to have the slave nodes, but for now a single container can manage the requirements. I'll get started on some of the basic framework with the image and testing capability. Will check in with you, to see if that's what you're looking for.
You can assign this issue to me.

**Comment by chelnak** [comment]
Thank you, assigned 👍

**Comment by satanb4** [comment]
Thanks for the update @chelnak

**Comment by chelnak** [comment]
Hi @satanb4. Appreciate your interest in this ticket however I have now got a working solution so am assigning it back to myself.

Thank you!
