### ISSUE TITLE
README.md should have an image of the app

### ISSUE THREAD

**Issue by chelnak** [chelnak/jenkins-tui#18]
It would be cool to have an image of the TUI app in the projects README.

**Comment by Hariprasad19036** [comment]
Hey, I would like to work on this issue under the hacktoberfest label!

**Comment by chelnak** [comment]
Hey @Hariprasad19036 feel free to submit a PR 👍

**Comment by Hariprasad19036** [comment]
Hey, I think you mistakenly self assigned this instead of assigning it to me. Also, in which version of python does this code run?

**Comment by chelnak** [comment]
Good spot.

It's been tested on 3.9.6 so far.
