### ISSUE TITLE
Add validation to the initial config wizard

### ISSUE THREAD

**Issue by chelnak** [chelnak/jenkins-tui#22]
When you start the app for the first time you will be asked a few questions. The answers will populate the config file that drives the app.

There is currently no validation on the input of these questions. They are just straight reads.

I think at a minimum there should be:

* Valid URL validation
* Empty inputs not allowed
* A final confirmation prompt

Source: https://github.com/chelnak/jenkins-tui/blob/6faff6831e4d609a4223f2f69628c2d2c636d6b3/src/jenkins_tui/app.py#L55

**Comment by rexdivakar** [comment]
Hey @chelnak  i would like to work on this please assign it to me

**Comment by chelnak** [comment]
Assigned ✅

**Comment by chelnak** [comment]
Hey @rexdivakar - I've just pushed a new version with a bunch of fixes. You might want to update your fork!
